# Generated by Django 3.0.6 on 2020-06-09 10:22

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='config',
            name='environment',
            field=django_mysql.models.ListCharField(models.CharField(max_length=100), max_length=1000, size=None),
        ),
        migrations.AlterField(
            model_name='config',
            name='neural_network_type',
            field=django_mysql.models.ListCharField(models.CharField(max_length=100), max_length=1000, size=None),
        ),
        migrations.AlterField(
            model_name='config',
            name='trainer_type',
            field=django_mysql.models.ListCharField(models.CharField(max_length=100), max_length=1000, size=None),
        ),
    ]
