# Generated by Django 3.0.7 on 2020-07-07 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20200622_1022'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='number',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
