# Generated by Django 3.0.7 on 2020-07-17 12:17

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_job_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='config',
            name='neural_network_type',
        ),
        migrations.RemoveField(
            model_name='config',
            name='trainer_population_size',
        ),
        migrations.RemoveField(
            model_name='config',
            name='trainer_sigma',
        ),
        migrations.RemoveField(
            model_name='config',
            name='trainer_type',
        ),
        migrations.RemoveField(
            model_name='job',
            name='neural_network_type',
        ),
        migrations.RemoveField(
            model_name='job',
            name='trainer_population_size',
        ),
        migrations.RemoveField(
            model_name='job',
            name='trainer_sigma',
        ),
        migrations.RemoveField(
            model_name='job',
            name='trainer_type',
        ),
        migrations.AddField(
            model_name='config',
            name='brain_neuron_activation',
            field=django_mysql.models.ListCharField(models.CharField(max_length=100), default=['relu'], max_length=1000, size=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='config',
            name='brain_neuron_activation_inplace',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='config',
            name='brain_normalize_input',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='config',
            name='brain_normalize_input_target',
            field=django_mysql.models.ListCharField(models.IntegerField(), default=[10], max_length=1000, size=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='config',
            name='brain_parameter_perturbations',
            field=django_mysql.models.ListCharField(models.CharField(max_length=100), default=[0.001], max_length=1000, size=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='config',
            name='brain_t_mask',
            field=django_mysql.models.ListCharField(models.CharField(max_length=100), default=['logarithmic'], max_length=1000, size=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='config',
            name='brain_t_mask_param',
            field=django_mysql.models.ListCharField(models.IntegerField(), default=[2], max_length=1000, size=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='config',
            name='brain_type',
            field=django_mysql.models.ListCharField(models.CharField(max_length=100), default=['CTRNN'], max_length=1000, size=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='config',
            name='brain_use_bias',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='config',
            name='brain_v_mask',
            field=django_mysql.models.ListCharField(models.CharField(max_length=100), default=['logarithmic'], max_length=1000, size=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='config',
            name='brain_v_mask_param',
            field=django_mysql.models.ListCharField(models.IntegerField(), default=2, max_length=1000, size=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='config',
            name='brain_w_mask',
            field=django_mysql.models.ListCharField(models.CharField(max_length=100), default=['logarithmic'], max_length=1000, size=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='config',
            name='brain_w_mask_param',
            field=django_mysql.models.ListCharField(models.IntegerField(), default=[8], max_length=1000, size=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='config',
            name='episode_runner_max_steps_penalty',
            field=django_mysql.models.ListCharField(models.IntegerField(), default=[0], max_length=1000, size=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='config',
            name='episode_runner_max_steps_per_run',
            field=django_mysql.models.ListCharField(models.IntegerField(), default=[0], max_length=1000, size=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='config',
            name='episode_runner_reuse_env',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='config',
            name='episode_runner_type',
            field=django_mysql.models.ListCharField(models.CharField(max_length=100), default=['Standard'], max_length=1000, size=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='config',
            name='optimizer_checkpoint_frequency',
            field=django_mysql.models.ListCharField(models.IntegerField(), default=[0], max_length=1000, size=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='config',
            name='optimizer_hof_size',
            field=django_mysql.models.ListCharField(models.IntegerField(), default=[5], max_length=1000, size=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='config',
            name='optimizer_population_size',
            field=django_mysql.models.ListCharField(models.IntegerField(), default=[10], max_length=1000, size=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='config',
            name='optimizer_sigma',
            field=django_mysql.models.ListCharField(models.CharField(max_length=100), default=[1.0], max_length=1000, size=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='config',
            name='optimizer_type',
            field=django_mysql.models.ListCharField(models.CharField(max_length=100), default=['CMA_ES'], max_length=1000, size=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='config',
            name='use_worker_processes',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='brain_neuron_activation',
            field=models.CharField(default='relu', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='brain_neuron_activation_inplace',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='brain_normalize_input',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='brain_normalize_input_target',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='brain_parameter_perturbations',
            field=models.DecimalField(decimal_places=3, default=0.001, max_digits=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='brain_t_mask',
            field=models.CharField(default='logarithmic', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='brain_t_mask_param',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='brain_type',
            field=models.CharField(default='CTRNN', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='brain_use_bias',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='brain_v_mask',
            field=models.CharField(default='logarithmic', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='brain_v_mask_param',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='brain_w_mask',
            field=models.CharField(default='logarithmic', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='brain_w_mask_param',
            field=models.IntegerField(default=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='episode_runner_max_steps_penalty',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='episode_runner_max_steps_per_run',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='episode_runner_reuse_env',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='episode_runner_type',
            field=models.CharField(default='Standard', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='optimizer_checkpoint_frequency',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='optimizer_hof_size',
            field=models.IntegerField(default=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='optimizer_population_size',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='optimizer_sigma',
            field=models.DecimalField(decimal_places=3, default=1.0, max_digits=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='optimizer_type',
            field=models.CharField(default='CMA_ES', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='use_worker_processes',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='config',
            name='brain_optimize_state_boundaries',
            field=django_mysql.models.ListCharField(models.CharField(max_length=100), max_length=1000, size=None),
        ),
        migrations.AlterField(
            model_name='job',
            name='brain_clipping_range_max',
            field=models.DecimalField(decimal_places=3, max_digits=5),
        ),
        migrations.AlterField(
            model_name='job',
            name='brain_clipping_range_min',
            field=models.DecimalField(decimal_places=3, max_digits=5),
        ),
        migrations.AlterField(
            model_name='job',
            name='brain_delta_t',
            field=models.DecimalField(decimal_places=3, max_digits=5),
        ),
        migrations.AlterField(
            model_name='job',
            name='brain_optimize_state_boundaries',
            field=models.CharField(max_length=100),
        ),
    ]
